// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wms.Inbound.Infrastructure;

#nullable disable

namespace Wms.Inbound.Infrastructure.Migrations
{
    [DbContext(typeof(InboundDbContext))]
    [Migration("20260710004207_AddOutboxPartitionKey")]
    partial class AddOutboxPartitionKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inbound")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wms.BuildingBlocks.Infrastructure.AuditLog.AuditLogRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Entity")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entity");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.HasKey("Id")
                        .HasName("pk_audit_log");

                    b.ToTable("audit_log", "infrastructure");
                });

            modelBuilder.Entity("Wms.BuildingBlocks.Infrastructure.DeadLetter.DeadLetterRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("DeadLetteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dead_lettered_at");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_dead_letter");

                    b.ToTable("dead_letter", "infrastructure");
                });

            modelBuilder.Entity("Wms.BuildingBlocks.Infrastructure.Inbox.InboxRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("HandlerType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("handler_type");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId", "HandlerType")
                        .HasName("pk_inbox");

                    b.ToTable("inbox", "infrastructure");
                });

            modelBuilder.Entity("Wms.BuildingBlocks.Infrastructure.Outbox.OutboxRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<string>("DeliveryClass")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("delivery_class");

                    b.Property<string>("LogicalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("logical_name");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PartitionKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("partition_key");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<string>("Traceparent")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("traceparent");

                    b.Property<string>("Tracestate")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("tracestate");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.ToTable("outbox", "infrastructure");
                });

            modelBuilder.Entity("Wms.Inbound.Domain.GRAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentRef")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("content_ref");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("file_name");

                    b.Property<Guid>("GoodsReceiptId")
                        .HasColumnType("uuid")
                        .HasColumnName("goods_receipt_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("modified_by");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_gr_attachment");

                    b.HasIndex("GoodsReceiptId")
                        .HasDatabaseName("ix_gr_attachment_goods_receipt_id");

                    b.ToTable("gr_attachment", "inbound");
                });

            modelBuilder.Entity("Wms.Inbound.Domain.GoodsReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("DockDoor")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("dock_door");

                    b.Property<string>("HoldReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("hold_reason");

                    b.Property<DateTimeOffset?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("modified_by");

                    b.Property<string>("PoRef")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("po_ref");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_goods_receipt");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_goods_receipt_status");

                    b.ToTable("goods_receipt", "inbound");
                });

            modelBuilder.Entity("Wms.Inbound.Domain.GoodsReceipt", b =>
                {
                    b.OwnsMany("Wms.Inbound.Domain.ValueObjects.Discrepancy", "Discrepancies", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("GoodsReceiptId")
                                .HasColumnType("uuid")
                                .HasColumnName("goods_receipt_id");

                            b1.Property<decimal>("Qty")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("qty");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("sku");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("type");

                            b1.HasKey("Id")
                                .HasName("pk_gr_discrepancy");

                            b1.HasIndex("GoodsReceiptId")
                                .HasDatabaseName("ix_gr_discrepancy_goods_receipt_id");

                            b1.ToTable("gr_discrepancy", "inbound");

                            b1.WithOwner()
                                .HasForeignKey("GoodsReceiptId")
                                .HasConstraintName("fk_gr_discrepancy_goods_receipt_goods_receipt_id");
                        });

                    b.OwnsMany("Wms.Inbound.Domain.ValueObjects.ExpectedLine", "ExpectedLines", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("ExpectedQty")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("expected_qty");

                            b1.Property<Guid>("GoodsReceiptId")
                                .HasColumnType("uuid")
                                .HasColumnName("goods_receipt_id");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("sku");

                            b1.Property<string>("Uom")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("uom");

                            b1.HasKey("Id")
                                .HasName("pk_gr_expected_line");

                            b1.HasIndex("GoodsReceiptId")
                                .HasDatabaseName("ix_gr_expected_line_goods_receipt_id");

                            b1.ToTable("gr_expected_line", "inbound");

                            b1.WithOwner()
                                .HasForeignKey("GoodsReceiptId")
                                .HasConstraintName("fk_gr_expected_line_goods_receipt_goods_receipt_id");
                        });

                    b.OwnsMany("Wms.Inbound.Domain.ValueObjects.QuantityCheck", "QuantityChecks", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("ActualQty")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("actual_qty");

                            b1.Property<decimal>("ExpectedQty")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("expected_qty");

                            b1.Property<Guid>("GoodsReceiptId")
                                .HasColumnType("uuid")
                                .HasColumnName("goods_receipt_id");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("sku");

                            b1.Property<string>("Variance")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("variance");

                            b1.HasKey("Id")
                                .HasName("pk_gr_quantity_check");

                            b1.HasIndex("GoodsReceiptId")
                                .HasDatabaseName("ix_gr_quantity_check_goods_receipt_id");

                            b1.ToTable("gr_quantity_check", "inbound");

                            b1.WithOwner()
                                .HasForeignKey("GoodsReceiptId")
                                .HasConstraintName("fk_gr_quantity_check_goods_receipt_goods_receipt_id");
                        });

                    b.OwnsMany("Wms.Inbound.Domain.ValueObjects.ReceivedLine", "ReceivedLines", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Batch")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("batch");

                            b1.Property<DateOnly?>("Expiry")
                                .HasColumnType("date")
                                .HasColumnName("expiry");

                            b1.Property<Guid>("GoodsReceiptId")
                                .HasColumnType("uuid")
                                .HasColumnName("goods_receipt_id");

                            b1.Property<decimal>("Qty")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("qty");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("sku");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("status");

                            b1.HasKey("Id")
                                .HasName("pk_gr_received_line");

                            b1.HasIndex("GoodsReceiptId")
                                .HasDatabaseName("ix_gr_received_line_goods_receipt_id");

                            b1.ToTable("gr_received_line", "inbound");

                            b1.WithOwner()
                                .HasForeignKey("GoodsReceiptId")
                                .HasConstraintName("fk_gr_received_line_goods_receipt_goods_receipt_id");
                        });

                    b.OwnsMany("Wms.Inbound.Domain.ValueObjects.RejectedLine", "RejectedLines", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("GoodsReceiptId")
                                .HasColumnType("uuid")
                                .HasColumnName("goods_receipt_id");

                            b1.Property<decimal>("Qty")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("qty");

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("reason");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("sku");

                            b1.HasKey("Id")
                                .HasName("pk_gr_rejected_line");

                            b1.HasIndex("GoodsReceiptId")
                                .HasDatabaseName("ix_gr_rejected_line_goods_receipt_id");

                            b1.ToTable("gr_rejected_line", "inbound");

                            b1.WithOwner()
                                .HasForeignKey("GoodsReceiptId")
                                .HasConstraintName("fk_gr_rejected_line_goods_receipt_goods_receipt_id");
                        });

                    b.OwnsMany("Wms.Inbound.Domain.ValueObjects.Resolution", "Resolutions", b1 =>
                        {
                            b1.Property<Guid>("DiscrepancyId")
                                .HasColumnType("uuid")
                                .HasColumnName("discrepancy_id");

                            b1.Property<string>("Action")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("action");

                            b1.Property<Guid>("GoodsReceiptId")
                                .HasColumnType("uuid")
                                .HasColumnName("goods_receipt_id");

                            b1.Property<string>("Note")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("note");

                            b1.HasKey("DiscrepancyId")
                                .HasName("pk_gr_resolution");

                            b1.HasIndex("GoodsReceiptId")
                                .HasDatabaseName("ix_gr_resolution_goods_receipt_id");

                            b1.ToTable("gr_resolution", "inbound");

                            b1.WithOwner()
                                .HasForeignKey("GoodsReceiptId")
                                .HasConstraintName("fk_gr_resolution_goods_receipt_goods_receipt_id");
                        });

                    b.OwnsMany("Wms.Inbound.Domain.ValueObjects.ScannedLine", "ScannedLines", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("ActualQty")
                                .HasPrecision(18, 3)
                                .HasColumnType("numeric(18,3)")
                                .HasColumnName("actual_qty");

                            b1.Property<string>("Batch")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("batch");

                            b1.Property<DateOnly?>("Expiry")
                                .HasColumnType("date")
                                .HasColumnName("expiry");

                            b1.Property<Guid>("GoodsReceiptId")
                                .HasColumnType("uuid")
                                .HasColumnName("goods_receipt_id");

                            b1.Property<string>("LineStatus")
                                .IsRequired()
                                .HasMaxLength(24)
                                .HasColumnType("character varying(24)")
                                .HasColumnName("line_status");

                            b1.Property<int>("ScanSequence")
                                .HasColumnType("integer")
                                .HasColumnName("scan_sequence");

                            b1.Property<string>("Sku")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("sku");

                            b1.HasKey("Id")
                                .HasName("pk_gr_scanned_line");

                            b1.HasIndex("GoodsReceiptId")
                                .HasDatabaseName("ix_gr_scanned_line_goods_receipt_id");

                            b1.ToTable("gr_scanned_line", "inbound");

                            b1.WithOwner()
                                .HasForeignKey("GoodsReceiptId")
                                .HasConstraintName("fk_gr_scanned_line_goods_receipt_goods_receipt_id");
                        });

                    b.Navigation("Discrepancies");

                    b.Navigation("ExpectedLines");

                    b.Navigation("QuantityChecks");

                    b.Navigation("ReceivedLines");

                    b.Navigation("RejectedLines");

                    b.Navigation("Resolutions");

                    b.Navigation("ScannedLines");
                });
#pragma warning restore 612, 618
        }
    }
}
