// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wms.Reporting.Persistence;

#nullable disable

namespace Wms.Reporting.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    [Migration("20260706065236_InitialReportingSchema")]
    partial class InitialReportingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("reporting")
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wms.BuildingBlocks.Infrastructure.Inbox.InboxRecord", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("HandlerType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("handler_type");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("EventId", "HandlerType")
                        .HasName("pk_inbox");

                    b.ToTable("inbox", "infrastructure");
                });

            modelBuilder.Entity("Wms.Reporting.ReadModels.DispatchSummary", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date")
                        .HasColumnName("period");

                    b.Property<decimal>("DispatchedVolume")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("dispatched_volume");

                    b.Property<int>("WaveThroughput")
                        .HasColumnType("integer")
                        .HasColumnName("wave_throughput");

                    b.HasKey("WarehouseId", "Period")
                        .HasName("pk_dispatch_summary");

                    b.ToTable("dispatch_summary", "reporting");
                });

            modelBuilder.Entity("Wms.Reporting.ReadModels.OperatorActivity", b =>
                {
                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date")
                        .HasColumnName("period");

                    b.Property<int>("PickCount")
                        .HasColumnType("integer")
                        .HasColumnName("pick_count");

                    b.Property<int>("PutawayCount")
                        .HasColumnType("integer")
                        .HasColumnName("putaway_count");

                    b.HasKey("OperatorId", "Period")
                        .HasName("pk_operator_activity");

                    b.ToTable("operator_activity", "reporting");
                });

            modelBuilder.Entity("Wms.Reporting.ReadModels.ReceivingSummary", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date")
                        .HasColumnName("period");

                    b.Property<int>("DiscrepancyCount")
                        .HasColumnType("integer")
                        .HasColumnName("discrepancy_count");

                    b.Property<int>("ReceiptCount")
                        .HasColumnType("integer")
                        .HasColumnName("receipt_count");

                    b.Property<decimal>("ReceivedQty")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("received_qty");

                    b.HasKey("SupplierId", "Period")
                        .HasName("pk_receiving_summary");

                    b.ToTable("receiving_summary", "reporting");
                });

            modelBuilder.Entity("Wms.Reporting.ReadModels.StockOnHandView", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<string>("Sku")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<string>("Batch")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("batch");

                    b.Property<decimal>("QtyOnHand")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("qty_on_hand");

                    b.HasKey("WarehouseId", "Sku", "Batch")
                        .HasName("pk_stock_on_hand_view");

                    b.ToTable("stock_on_hand_view", "reporting");
                });
#pragma warning restore 612, 618
        }
    }
}
